# SConscript - build lab2 under Linux

SOURCE = "lab2_main.cpp";
TARGET = "lab2"

SHADERS = "simple.frag simple.vert";
TEXTURES = "explosion.png  flake.ppm  floor.jpg  white-marble.ppm";

Import( "env" );
Import( "libGLUTIL" );
Import( "libLinmath" );

from SCript.Stages import config, build, install;

dataFiles = SHADERS.split() + TEXTURES.split();

@build
def build_lab():
	obj = [env.Object(src) for src in SOURCE.split()];

	lib = [libGLUTIL, libLinmath];
	prg = env.Program( target = TARGET, source = obj + lib );
	
	# The following line ensures that files are moved to the build dir
	dat = [env.File(data) for data in dataFiles];

	return prg; 

@install
def install_lab():
	dataPath = "#share/" + TARGET;

	iprog = env.Install( "#bin", TARGET );
	idata = [env.Install( dataPath, data ) for data in dataFiles];

	return [iprog] + idata;

# EOF vim:syntax=python:foldmethod=marker:ts=4:noexpandtab
